### ISSUE TITLE
Error when trying to get botlist

### ISSUE THREAD

**Issue by theNILV** [Gortaf/TheKeeperBot#1]
I have been trying to get the script work but it keeps giving me this error.
Filename: CORE_StreamlabsSystem.py
Function: getBots
LineNr: 128
Message: Could not find file 'mypath:\scripts\TheKeeperBot-master\Main\lib\bots.txt'

Error keeps happening when i'm clicking "UPDATE BOT LIST" Any idea what i might be doing wrong?

**Comment by Gortaf** [comment]
Hi! Thank you for trying the script and sorry to hear that.
Have you entered your python lib path in the script UI (the same you put in the global script settings) and saved settings before clicking "UPDATE BOT LIST"?
If no, try to do that, as the script requires the python path to get selenium to work properly. The python path needs to be exactly what you put in the global script settings when first setting up streamlabs chatbot. Something like "D:\Python27\Lib". (This makes me realise that the UI still says "interpreter path", which is misleading. Will change) and don't forget to "save settings" after entering the python path!

Hope this helps! And keep me posted if it still doesn't work :)

**Comment by theNILV** [comment]
I do have the python path on the script, but it keeps giving me the error regardless

**Comment by Gortaf** [comment]
Interesting. From what I'm able to replicate, it might be selenium not having enough time to load the twitchinsight page, and thus failing to find the bots and the rest of the script being unable to create the bot file because of this.
I've updated the code to give selenium a bit more time to load, and give more debugging options if that doesn't fix it. Would you mind downloading it again and installing it please?
If it still won't work enable "show webscrap console" from the debugging settings, save settings and try to click on "UPDATE BOT LIST". This will show the console for the webscrap subprocess, so I can have a look at it.
Thank you!

**Comment by theNILV** [comment]
I downloaded it again and tried but still getting same errors, Also can't seem to open the console with that option. When i put "show webscrap console" I can see the console quickly blinking and then going away.

**Comment by Gortaf** [comment]
Ah interesting! This narrows it down quite a bit, as the console blinking away means that the error comes before the webdriver is opened. In that case it's most likely an import error. So I checked and apparently pip is not native in python 2.7.13 (which I thought it was). In debug there should now be a button with "get/update pip". Click it, it will install pip, which should fix the import error.
Thank you!

**Comment by theNILV** [comment]
Awesome! it works now, thanks! :)

**Comment by Gortaf** [comment]
Awsome! Glad it works now!

Thanks for your patience :)
